### ISSUE TITLE
Gauche still spelt wrong in corrections.yaml

### ISSUE THREAD

**Issue by cjholdship** [VlachosGroup/PythonGroupAdditivity#14]
Sorry to be a pain but gauche is now spelt 'gauech' instead of gauche in the same file as before.

**Comment by wittregr** [comment]
Thanks for the feedback. Not a pain. Sorry I got it wrong again. Hope v1.65 corrects that.

**Comment by mpnunez** [comment]
Have you guys considered using automated tests like pytest? I'm not familiar with PythonGroupAdditivity, but automated tests can help prevent releasing code with small errors like this.

**Comment by wittregr** [comment]
Yes...We have implemented unittest and have 42 unit tests setup. Unfortunately, I did not run unittest after issuing a new version since it was "only" a minor spelling change correction. I was unaware that a summer student working for Jon and me this past summer had promoted code that had not been included in a previously released build. He said he ran unittest and verified that the code worked. It did not and caused this issue. Jon and I spent a couple of hours backing out commits to get back to working code. I should have done more testing when he finished his work and not let him merge his commits. Lesson learned.
