### ISSUE TITLE
Nitro group

### ISSUE THREAD

**Issue by l0d0v1c** [VlachosGroup/PythonGroupAdditivity#16]
It seems there is an issue with nitroorganic eg:
from pgradd.GroupAdd.Library import GroupLibrary
import pgradd.ThermoChem
lib = GroupLibrary.Load('BensonGA')
descriptors = lib.GetDescriptors("C[N+](=O)[O-]")

Sub group not assigned:
[H]C([H])([H])[N+](=O)[O-] Atom symbol: N #radicalE: 0
Connectivity:
C SINGLE
O DOUBLE
O SINGLE
 Occured  at atom number 1

Do you know why?

Yours

**Comment by wittregr** [comment]
Unfortunately, the Benson database is limited. At this time it only supports C, H, and O. The scheme could be extended to support any atoms for which there is additivity data. We have not done this since our work rarely requires additional atoms. The software is open source so you are welcome to contribute to the database.

**Comment by l0d0v1c** [comment]
thank you. I eventualy did it by deep learning https://www.researchgate.net/project/Formulation-by-deep-learning
